# Wave 1-2: Bug Fixes

**Owner**: Claude-A
**Worktree**: `wt-bugfixes`
**Branch**: `fix/wave-1-2-bugs`
**Status**: Pending (blocked by Wave 0)

---

## Open Issues (10 Total - ALL Must Be Fixed)

### [ ] C-1: STT Discrepancy (BUG 2) - P1

**Problem**: Agent understands correctly, but chat transcription is wrong.

**Examples**:
- Said: "vai" -> Chat shows: "bye"
- Said: "la Spezia" -> Agent responds well, chat shows something else

**Hypothesis**: Two separate STT systems? One for agent, one for UI.

**Files to investigate**: Voice transcription logic, chat display

### [ ] C-2: Session Recap + Memory (BUG 4) - P1

**Problem**: When closing voice conversation, missing:
1. Automatic recap of what was done
2. Correct memory save
3. Parent insights generated
4. Remember previous session on next open

**Note**: Feature should already exist - verify it works.

**Files involved**: `conversation-memory.ts`, session summary logic

### [ ] C-3: Input Bar + Voice Panel Not Fixed (BUG 9) - P1

**Problem**: In chat/voice with maestros, elements that should be fixed scroll with content.

**Expected Layout**:
```
+-------------------------------------+--------------+
|                                     |              |
|    CHAT MESSAGES (SCROLLS)          |  VOICE PANEL |
|    + TOOL CONTENT                   |  (FIXED)     |
|                                     |              |
+-------------------------------------+              |
| [Tool buttons] [Input "Parla..."]   |              |
| (FIXED AT BOTTOM - sticky/fixed)    |              |
+-------------------------------------+--------------+
```

**Likely fix**: CSS sticky/fixed positioning

### [ ] C-4: Azure OpenAI Costs Empty (BUG 24) - P1

**Problem**: In Settings -> Statistics, "Azure OpenAI Costs" card is empty.

**Expected**: Tokens used, estimated cost, breakdown by model, trend.

**Investigate**: Is Azure usage tracking implemented? Costs API integrated?

### [ ] C-5: Conversation History per Coach/Buddy (BUG 32) - P0

**Problem**: Conversation history is GLOBAL instead of per-character.

**Current state**:
- Talk to Melissa about X
- Switch to Andrea
- Andrea sees Melissa's history (WRONG)

**Expected**: Each Coach/Buddy has separate history. Zero leak between characters.

**Files involved**: Conversation storage, memory system, character context

### [ ] C-6: Timer + XP Bar (BUG 3) - P2

**Problem**: Missing gamification elements in maestro conversations.

**Requirements**:
1. **Conversation Timer**: Show how long the current session has been going in the right panel (where voice conversation is displayed)
2. **XP Progress Bar**: In the XP section, show a bar indicating how much more time/engagement is needed to level up

**Benefits**: Gamification, student motivation, progress visibility

**Implementation Notes**:
- Timer: Add elapsed time display to voice panel component
- XP Bar: Calculate progress percentage from current XP vs next level threshold
- Store session start time in conversation state

**Files involved**: Voice panel component, XP/gamification store, conversation state

### [ ] C-7: Demo Tool Non Rispetta Accessibilita (BUG 10) - P1

**Problem**: The Demo tool (generates interactive content) does NOT apply user's accessibility settings.

**Settings to respect**:
- Dyslexic font (OpenDyslexic) if active
- High contrast color scheme if active
- Custom font size
- Text spacing
- Other accessibility profiles (`src/lib/accessibility/`)

**Expected**: ALL content generated by Demo tool must inherit user's accessibility settings.

**Implementation Notes**:
- Demo tool likely uses iframe for sandboxing
- Need to inject CSS with accessibility settings into iframe
- Read user's accessibility profile from context/store
- Apply transformations before rendering

**Files involved**:
- `src/components/education/knowledge-hub/renderers/demo-renderer.tsx`
- `src/lib/accessibility/` (profiles)
- CSS injection logic for iframe

### [ ] C-8: Audio Ambientale Cafe Non Realistico (BUG 25) - P2

**Problem**: The "Starbucks" ambient sound doesn't resemble a bar/coffee shop at all.

**Expected**:
- People chattering in background
- Typical bar sounds (cups, coffee machine, door opening)
- Realistic coffee shop atmosphere

**Current**: Unidentifiable/unrealistic sound

**Implementation Notes**:
1. Find suitable royalty-free audio (Freesound.org, Pixabay, etc.)
2. Attributes needed: cafe ambience, background chatter, ~60-120 seconds loop
3. Replace existing audio file or add new one
4. Update audio configuration to use new file

**Files involved**:
- `public/audio/ambient/` (create if doesn't exist)
- Ambient audio configuration
- Audio player component

### [ ] C-9: Contatori Header Non Si Aggiornano (BUG 28) - P0

**Problem**: I contatori nell'header mostrano sempre 0 e non si aggiornano MAI:
- Streak: 0
- Flashcard: 0
- Tempo: 0m
- XP: 0

**Expected**:
- Contatori aggiornati in REAL-TIME
- Tempo incrementa mentre si usa l'app
- XP aumenta dopo attività
- Streak mostra giorni consecutivi
- Flashcard mostra cards studiate oggi

**Correlation**: Related to BUG 22/23 (statistiche/telemetria) - same underlying issue.

**Files involved**: Header component, stats store, real-time updates, telemetry

### [ ] C-10: Demo/Tools Si Aprono in Nuova Pagina (BUG 20) - P1

**Problem**: Le demo interattive (e altri tool) si aprono in una NUOVA TAB del browser invece che in un frame/modal dentro l'app.

**Expected**:
- Click su demo apre in frame/panel dentro la pagina
- Mai aprire nuove tab
- Esperienza seamless senza context switch

**Files involved**: Link handling, demo viewer component, demo-renderer.tsx

---

## Execution Plan

### Wave 1: P0 Bug Fixes (Sequential)

| Step | Task | Owner | Files Touched | Dependencies |
|------|------|-------|---------------|--------------|
| 1.1 | C-5: History per Coach/Buddy | Claude-A | `conversation-flow-store.ts`, `conversation-memory.ts` | Wave 0.3 |
| 1.2 | C-9: Header Counters Real-time | Claude-A | Header, stats store, telemetry | 1.1 |

### Wave 2: P1 + P2 Bug Fixes (Sequential)

| Step | Task | Owner | Files Touched | Dependencies |
|------|------|-------|---------------|--------------|
| 2.1 | C-2: Session Recap + Memory | Claude-A | `conversation-memory.ts`, session logic | 1.1 |
| 2.2 | C-3: Layout sticky | Claude-A | `materiali-conversation.tsx` (CSS only) | 1.1 |
| 2.3 | C-4: Azure costs | Claude-A | `diagnostics-tab.tsx`, Azure API | 1.1 |
| 2.4 | C-1: STT investigation | Claude-A | Voice transcription files | 1.1 |
| 2.5 | C-6: Timer + XP Bar | Claude-A | Voice panel, XP store | 2.1 |
| 2.6 | C-7: Demo Accessibility | Claude-A | `demo-renderer.tsx`, accessibility lib | 2.1 |
| 2.7 | C-8: Cafe Audio | Claude-A | `public/audio/`, audio config | 2.1 |
| 2.8 | C-10: Demo in frame (not new tab) | Claude-A | `demo-renderer.tsx`, link handling | 2.6 |

### Completion Criteria

- [ ] All 10 issues resolved
- [ ] `npm run typecheck && npm run lint && npm run build` passes
- [ ] PR `fix/wave-1-2-bugs` created
- [ ] Status updated in TODAY.md

---

## Sign-off Checklist

| Step | Task | Status | Date | Signature |
|------|------|--------|------|-----------|
| 1.1 | C-5: History per Coach/Buddy (P0) | [ ] | | Claude-A |
| 1.2 | C-9: Header Counters Real-time (P0) | [ ] | | Claude-A |
| 2.1 | C-2: Session Recap + Memory (P1) | [ ] | | Claude-A |
| 2.2 | C-3: Layout sticky (P1) | [ ] | | Claude-A |
| 2.3 | C-4: Azure costs (P1) | [ ] | | Claude-A |
| 2.4 | C-1: STT Discrepancy (P1) | [ ] | | Claude-A |
| 2.5 | C-6: Timer + XP Bar (P2) | [ ] | | Claude-A |
| 2.6 | C-7: Demo Accessibility (P1) | [ ] | | Claude-A |
| 2.7 | C-8: Cafe Audio (P2) | [ ] | | Claude-A |
| 2.8 | C-10: Demo in frame (P1) | [ ] | | Claude-A |
| - | PR created | [ ] | | Claude-A |

---

## Evidence Section (per VERIFICATION-PROCESS.md)

| Check | Result | Timestamp |
|-------|--------|-----------|
| `npm run typecheck` | [ ] PASS / FAIL | |
| `npm run lint` | [ ] PASS / FAIL | |
| `npm run build` | [ ] PASS / FAIL | |
| `grep -ri PLACEHOLDER src/` | [ ] 0 matches | |
| Manual testing | [ ] Done | |

**Verified by**: _________________ **Date**: _________________

**PR Compliance**: Before creating PR, complete `docs/EXECUTION-CHECKLIST.md`

---

*Parent document: [TODAY.md](../TODAY.md)*
*Created: 3 January 2026*
*Updated: 3 January 2026 (Added BUG 3, 10, 25, 28, 20 - zero deferred)*
