let tokenChart, modelChart, distChart;
function chartOpts(){return{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{labels:{color:"#c8d0e8",font:{family:"JetBrains Mono",size:10},boxWidth:12,padding:8}},tooltip:{backgroundColor:"#0f1424",borderColor:"#1a2040",borderWidth:1,titleFont:{family:"JetBrains Mono"},bodyFont:{family:"JetBrains Mono"},callbacks:{label:(ctx)=>`${ctx.dataset.label}: ${fmt(ctx.raw)}`}},zoom:{pan:{enabled:true,mode:"x"},zoom:{wheel:{enabled:true},pinch:{enabled:true},mode:"x"}}},scales:{x:{grid:{color:"#1a2040"},ticks:{color:"#5a6080",font:{size:9},maxRotation:0}},y:{grid:{color:"#1a2040"},ticks:{color:"#5a6080",font:{size:10},callback:(v)=>fmt(v)}}}}}
function renderTokenChart(daily){const labels=daily.map(d=>d.day.substring(5)),input=daily.map(d=>d.input||0),output=daily.map(d=>d.output||0);if(tokenChart)tokenChart.destroy();tokenChart=new Chart($("#token-chart"),{type:"line",data:{labels,datasets:[{label:"Input",data:input,borderColor:"#00e5ff",backgroundColor:"rgba(0,229,255,0.1)",fill:true,tension:.4,borderWidth:2,pointRadius:1,pointHoverRadius:4},{label:"Output",data:output,borderColor:"#ff2daa",backgroundColor:"rgba(255,45,170,0.08)",fill:true,tension:.4,borderWidth:2,pointRadius:1,pointHoverRadius:4}]},options:chartOpts()})}
function renderModelChart(models){const total=models.reduce((s,m)=>s+(m.cost||0),0),hdr=document.querySelector("#widget-cost .widget-title");if(hdr)hdr.innerHTML=`Cost by Model <span style="float:right;color:var(--gold);font-size:11px">Total: $${total.toFixed(2)}</span>`;const colors=["#00e5ff","#ff2daa","#ffb700","#00ff88","#ff3355","#8855ff","#44ddff","#ffdd44"];if(modelChart)modelChart.destroy();modelChart=new Chart($("#model-chart"),{type:"doughnut",data:{labels:models.map(m=>(m.model||"?").replace("claude-","")),datasets:[{data:models.map(m=>m.cost||0),backgroundColor:colors.slice(0,models.length),borderColor:"#0a0e1a",borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"right",labels:{color:"#c8d0e8",font:{family:"JetBrains Mono",size:10},padding:8,boxWidth:12}},tooltip:{callbacks:{label:(ctx)=>`$${ctx.raw.toFixed(2)}`}}},cutout:"65%"}})}
const distGaugeTextPlugin={id:"distGaugeText",afterDraw(chart,args,opts){if(!opts||opts.total===undefined)return;const pt=chart.getDatasetMeta(0).data[0];if(!pt)return;const{ctx}=chart;ctx.save();ctx.textAlign="center";ctx.fillStyle="#e6eeff";ctx.font="700 22px JetBrains Mono";ctx.fillText(String(opts.total),pt.x,pt.y-2);ctx.fillStyle="#5a6080";ctx.font="11px JetBrains Mono";ctx.fillText(opts.label||"tasks",pt.x,pt.y+16);ctx.restore()}};
function renderDist(dist){const cm={done:"#00ff88",in_progress:"#ffb700",submitted:"#00e5ff",blocked:"#ff3355",pending:"#5a6080",cancelled:"#ff3355",skipped:"#3a3f55"},safeDist=dist&&dist.length?dist:[{status:"pending",count:0}],total=safeDist.reduce((sum,item)=>sum+(item.count||0),0),hdr=document.querySelector("#widget-dist .widget-title");if(hdr)hdr.innerHTML=`Task Distribution <span style="float:right;color:var(--gold);font-size:11px">${fmt(total)} tasks</span>`;if(distChart)distChart.destroy();distChart=new Chart($("#dist-chart"),{type:"doughnut",plugins:[distGaugeTextPlugin],data:{labels:safeDist.map(d=>d.status.replace("_"," ")),datasets:[{data:safeDist.map(d=>Math.max(d.count||0,total?0:1)),backgroundColor:safeDist.map(d=>cm[d.status]||"#5a6080"),borderColor:"#0a0e1a",borderWidth:2,hoverOffset:8,spacing:3,borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,layout:{padding:{top:6,bottom:6,left:6,right:6}},plugins:{distGaugeText:{total,label:"tasks"},legend:{position:"right",labels:{color:"#c8d0e8",font:{family:"JetBrains Mono",size:10},padding:10,boxWidth:10,usePointStyle:true,pointStyle:"circle"}},tooltip:{callbacks:{label:(ctx)=>{const value=Number(ctx.raw||0),pct=total?Math.round(value/total*100):0;return `${ctx.label}: ${fmt(value)}${total?` (${pct}%)`:""}`}}}},cutout:"72%"}})}
window.resetTokenZoom=()=>tokenChart&&tokenChart.resetZoom();
window.renderTokenChart=renderTokenChart;window.renderModelChart=renderModelChart;window.renderDist=renderDist;
window._charts={get token(){return tokenChart},get model(){return modelChart},get dist(){return distChart}};
